version: '3.8'
services:
  # PHP Service
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: ${APP_SLUG}_php
    restart: unless-stopped
    environment:
      SERVICE_NAME: ${APP_SLUG}_php
      SERVICE_TAGS: ${APP_ENV}
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app_network

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: ${APP_SLUG}_nginx
    restart: unless-stopped
    ports:
      - "8888:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network

  # Mariadb Service
  database:
    image: mariadb:latest
    container_name: ${APP_SLUG}_database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      SERVICE_TAGS: ${APP_ENV}
      SERVICE_NAME: ${APP_SLUG}_database
    volumes:
      - ./storage-db:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app_network

  # Redis service
  redis:
    image: redis:latest
    container_name: ${APP_SLUG}_redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
    networks:
      - app_network

  # Phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8585:80"
    container_name: ${APP_SLUG}_phpmyadmin
    depends_on:
      - database
    environment:
      PMA_HOST: ${DB_HOST}
    networks:
      - app_network

  # Mailhog
  mailhog:
    image: mailhog/mailhog
    restart: unless-stopped
    container_name: ${APP_SLUG}_mailhog
    environment:
      SERVICE_TAGS: ${APP_ENV}
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      - app_network

# Docker Networks
networks:
  app_network:
    driver: bridge